2023-12-17 20:24:32 INFO ====== WebDriver manager ======
2023-12-17 20:24:34 INFO Get LATEST chromedriver version for google-chrome
2023-12-17 20:24:34 INFO Get LATEST chromedriver version for google-chrome
2023-12-17 20:24:35 INFO There is no [win64] chromedriver "120.0.6099.71" for browser google-chrome "120.0.6099" in cache
2023-12-17 20:24:35 INFO Get LATEST chromedriver version for google-chrome
2023-12-17 20:24:35 INFO WebDriver version 120.0.6099.71 selected
2023-12-17 20:24:35 INFO Modern chrome version https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/win32/chromedriver-win32.zip
2023-12-17 20:24:35 INFO About to download new driver from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/win32/chromedriver-win32.zip
2023-12-17 20:24:36 INFO Driver downloading response is 200
2023-12-17 20:24:38 INFO Get LATEST chromedriver version for google-chrome
2023-12-17 20:24:38 INFO Driver has been saved in cache [C:\Users\Админ\.wdm\drivers\chromedriver\win64\120.0.6099.71]
2023-12-17 20:24:42 INFO Test1 Starting
2023-12-17 20:24:50 INFO Test2 Starting
2023-12-17 20:24:51 INFO Test3 Starting
2023-12-17 20:24:53 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:53 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:53 ERROR Element ('xpath', '//*[@id="create-item"]/div/div/div[1]/div/label/input') not found
2023-12-17 20:24:53 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:53 ERROR Element ('xpath', '//*[@id="create-item"]/div/div/div[2]/div/label/span/textarea') not found
2023-12-17 20:24:53 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:53 ERROR Element ('xpath', '//*[@id="create-item"]/div/div/div[3]/div/label/span/textarea') not found
2023-12-17 20:24:53 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 INFO Test4 Starting
2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 ERROR Element ('xpath', '//*[@id="contact"]/div[1]/label/input') not found
2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 ERROR Element ('xpath', '//*[@id="contact"]/div[2]/label/input') not found
2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:24:58 ERROR Element ('xpath', '//*[@id="contact"]/div[3]/label/span/textarea') not found
2023-12-17 20:24:58 ERROR Find element exception
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 14, in find_element
    element = WebDriverWait(self.driver, time).until(EC.presence_of_element_located(locator),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 80, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x00319E7B]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:25:01 INFO Get alert text
2023-12-17 20:25:01 ERROR Exception with alert
Traceback (most recent call last):
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\HW4\BaseApp.py", line 39, in alert
    alert_obj = self.driver.switch_to.alert
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 58, in alert
    _ = alert.text
        ^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\common\alert.py", line 58, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Админ\PycharmProjects\pythonProjecttest\GB_homework\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.109)
Stacktrace:
	GetHandleVerifier [0x00676E73+174291]
	(No symbol) [0x005A0AC1]
	(No symbol) [0x002B6FF6]
	(No symbol) [0x0029EFE7]
	(No symbol) [0x0030B53B]
	(No symbol) [0x002CDEC4]
	(No symbol) [0x00306DA6]
	(No symbol) [0x002E1034]
	(No symbol) [0x002E1F8D]
	GetHandleVerifier [0x007149CC+820268]
	sqlite3_dbdata_init [0x007D4EBE+652494]
	sqlite3_dbdata_init [0x007D48D9+650985]
	sqlite3_dbdata_init [0x007C962C+605244]
	sqlite3_dbdata_init [0x007D586B+654971]
	(No symbol) [0x005AFEBC]
	(No symbol) [0x005A8428]
	(No symbol) [0x005A854D]
	(No symbol) [0x00595858]
	BaseThreadInitThunk [0x769DFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x771C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7C3E+238]

2023-12-17 20:25:01 INFO None
